CREATE TABLE [dbo].[comments](
	[id_comments] [int] IDENTITY(1,1) NOT NULL,
	[text] [nvarchar](100) COLLATE Ukrainian_CI_AS NULL,
	[id_client] [int] NULL,
 CONSTRAINT [PRIMARY001] PRIMARY KEY CLUSTERED 
(
	[id_comments] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = OFF),
 CONSTRAINT [id_comments] UNIQUE NONCLUSTERED 
(
	[id_comments] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = OFF)
)


